#' Dummy Single-arm Trial Data for Unanchored MAIC
#'
#' These datasets contains adsl_sat, adtte_sat, adrs_sat,
#' agd_sat (AgD of effect modifiers), pseudo_ipd_sat (AgD, tte data)
#' @format **adsl_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @format **adtte_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @format **pseudo_ipd_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **agd**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **centered_ipd_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **adrs_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @source These datasets are generated by the dummy_unanchored.R script.
#' @name unanchored-data
#' @keywords dataset
"adsl_sat"

#' @rdname unanchored-data
"adtte_sat"

#' @rdname unanchored-data
"pseudo_ipd_sat"

#' @rdname unanchored-data
"agd"

#' @rdname unanchored-data
"centered_ipd_sat"

#' @rdname unanchored-data
"adrs_sat"



#' Dummy Trial Data for anchored MAIC
#'
#' These datasets contains adsl_twt, adtte_twt,
#' centered_ipd_twt,  pseudo_ipd_twt (AgD, tte data)
#'
#' @format **adsl_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @format **adtte_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @format **pseudo_ipd_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **centered_ipd_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @source These datasets are generated by the dummy_anchored.R script.
#' @name anchored-data
#' @keywords dataset
"adsl_twt"

#' @rdname anchored-data
"adtte_twt"

#' @rdname anchored-data
"pseudo_ipd_twt"

#' @rdname anchored-data
"centered_ipd_twt"
