#' Dummy Single-arm Trial Data for Unanchored MAIC
#'
#' These datasets contains adsl_sat, adtte_sat, adrs_sat,
#' agd (AgD of effect modifiers), pseudo_ipd_sat (AgD, tte data)
#' @format **adsl_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @format **adtte_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @format **pseudo_ipd_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **agd**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **centered_ipd_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#' @format **adrs_sat**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
#' @source These datasets are generated by the dummy_unanchored.R script.
#' @name unanchored-data
#' @keywords dataset
"adsl_sat"

#' @rdname unanchored-data
"adtte_sat"

#' @rdname unanchored-data
"pseudo_ipd_sat"

#' @rdname unanchored-data
"agd"

#' @rdname unanchored-data
"centered_ipd_sat"

#' @rdname unanchored-data
"adrs_sat"



#' Dummy Trial Data for anchored MAIC
#'
#' These datasets contains adsl_twt, adtte_twt,
#' centered_ipd_twt,  pseudo_ipd_twt (AgD, tte data)
#'
#' @source These datasets are generated by the dummy_anchored.R script.
#' @name anchored-data
#' @keywords dataset
NULL

#' @rdname anchored-data
#' @format **adsl_twt**: a data frame with 1000 rows and 9 columns:
#'   \describe{
#'     \item{X}{The ID of the patients.}
#'     \item{USUBJID}{Unique subject identifiers for patients.}
#'     \item{ARM}{Assigned treatment arm.}
#'     \item{AGE}{Age in years at baseline.}
#'     \item{SEX}{Sex of patient recorded as character "Male"/"Female"}
#'     \item{SMOKE}{Smoking status at baseline as integer 0/1}
#'     \item{ECOG0}{ECOG score at baseline as integer 0/1}
#'     \item{N_PR_THER}{Number of prior therapies received as integer 1, 2, 3, 4}
#'     \item{SEX_MALE}{Indicator of SEX == "Male" as numeric 1/0}
#'   }
#'
"adsl_twt"

#' @rdname anchored-data
#' @format **adtte_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
#'
"adtte_twt"

#' @rdname anchored-data
#' @format **pseudo_ipd_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
"pseudo_ipd_twt"

#' @rdname anchored-data
#' @format **centered_ipd_twt**: a data frame with xx rows and x columns:
#'   \describe{
#'     \item{id}{The ID of the patients.}
#'   }
"centered_ipd_twt"
